zn_school_deparment_admission_score(
    id: ,
    zsdp_id: zh_school_department_project表id,
    atar_score: ATAR分数,
    ukalevel3_score: UKAlevel三科分数,
    ukalevel3_score1: UKAlevel三科分数（一）,
    ukalevel3_score2: UKAlevel三科分数（二）,
    ukalevel3_score3: UKAlevel三科分数（三）,
    ukalevel4_score: UKAlevel四科分数,
    ib_score: IB分数,
    sat_score: SAT分数,
    act_score: ACT分数,
    ap_score: AP分数,
    ossd_score: OSSD分数,
    bc_score: BC分数,
    gaokao_score: GAOKAO分数,
    c9_score: C9均分分数,
    s985_score: 985均分分数,
    s211_score: 211均分分数,
    sn211_score: 非211均分分数,
    b_accept_md_bg: 是否接受跨专业/需要相关背景,
    atar_ask: ATAR要求,
    ukalevel3_ask: UKAlevel三科要求,
    ukalevel4_ask: UKAlevel四科要求,
    ib_ask: IB要求,
    sat_ask: SAT要求,
    act_ask: ACT要求 ,
    ap_ask: AP要求,
    ossd_ask: OSSD要求,
    bc_ask: BC要求,
    gaokao_ask: GAOKAO要求,
    c9_ask: C9均分要求,
    s985_ask: 985均分要求,
    s211_ask: 211均分要求,
    sn211_ask: 非211均分要求,
    accept_md_bg: 是否接受跨专业/需要相关背景,
    delete_status: ,
    create_by: zh_school_department_project表id,
    update_by: zh_school_department_project表id,
    create_time: (0),
    update_time: (0) ,)

