CREATE TABLE zn_school_info
(
    id:,
    country_id: 国家ID,
    country_name: 国家名称,
    chinese_name: 院校中文名,
    english_name: 院校英文名,
    logo_url: 院校logo,
    cover_url: 院校背景图,
    market_tags: 院校标签 逗号分隔,
    city_path: 院校位置,
    website: 官网地址,
    spider_id: 0 爬虫ID,
    delete_status: 0 是否删除 0-未删除, 1-已删除,
    create_by: 填写人,
    update_by: 更新人,
    create_name: 创建人名称,
    update_name: 更新人名称,
    create_time: 创建时间,
    update_time: 更新时间,
    comment_tags: 评价标签,
    is_popular: 是否热门院校 1：是 0否,
    fans_base_total: 关注基数,
    school_sort: 院校排序,
    fans_total: 关注人数,
    school_abbreviations: 院校简称,
    fee_dimension: 申请费支付方式1-按院校、 2按专业、3其他,
    apply_cycle_algorithm: 申请周期-算法统计(自然日),
    apply_cycle_manual : 申请周期-人工填写(自然日),
    period :,
    weight 排序权重（23.7-24.1 的申请数）,
)

SET FOREIGN_KEY_CHECKS = 1;
